### ISSUE TITLE
No sounds. 

### ISSUE THREAD

**Issue by Superelmanu** [scooper4711/obsidian-syrinscape#4] opened 2024-06-28 16:16 UTC
Hi, I'm with the last version of Obsidian entered the token from Syrinscape with an empty test vault with only obsidian-syrinscape, Token had been reset and reimplemented in Obsidian. 
When in reading mode I can push the button but no sound.
I do have sound from obsidian when playing recordings, but nothing plays from pushing the play button from the plugin. 

Am I missing something?

**Comment by scooper4711** [comment] 2024-06-28 17:02
This plugin controls the online Syrinscape player. You need to have the Syrinscape online player running either as a standalone app or the web browser. No sound will come from just obsidian. 

I prefer the standalone personally. 

https://syrinscape.com/download/

**Comment by scooper4711** [comment] 2024-06-28 17:53
@Superelmanu I’ve updated the [README](https://github.com/scooper4711/obsidian-syrinscape) file to make the requirements more explicit. Let me know if that helps. 

I’m also going to log a feature request (#5) to embed the online player in the plugin. I’m not sure if that’s possible, but it sure is an interesting idea. Thank you!

**Comment by Superelmanu** [comment] 2024-06-28 23:34
Thank you for the help, it's now working. 
Only found a small limitation. If you are using a laser (as an example) you can queue the sound one after the other, but you can't click the play button to have multiple laser shooting at once as you can using the player (online or installed).

Embedding the player may solve this?

**Comment by scooper4711** [comment] 2024-06-29 14:16
I can see that the API requests to the online player are going out just as fast as you can click them. You can open the console to view this with Cmd-Option-I if you want.
What I noticed is it depends on the sound. E.g. this sound, even though it's an "element" plays on a loop and shows up with a "SFX" icon in the web UI `syrinscape:element:1163531:Heavy lasers (eob In the marrow)`. So each call to "play" just tells the UI "yes, please start this loop". Since the loop is already started, you don't get much. 

This sound, on the other hand, will go "pew" just as fast as you can click in either Obsidian or the Web UI:
`syrinscape:element:3089:Laser`
It's one of the global one-shots.

I may need to do some digging and display the "stop" button for more than just "mood". It looks like some "elements" need a stop button too. And a stop button would give a clear indication that a noise isn't right for multi-clicking play. Logged issue #6

**Comment by scooper4711** [comment] 2024-06-29 14:17
@Superelmanu  - I'm not sure that the element id's translate from user to user, but if you give me the whole macro you used (everything between the backticks) I'll see if I can confirm you had a SFX instead of a one-shot element.

**Comment by scooper4711** [comment] 2024-06-30 19:31
@Superelmanu - I think that the version I just released last night will help you out significantly. I've re-vamped the autocomplete and I've also changed it so instead of "element", you specify if the element is a oneshot, music, or sfx. Both music and sfx (as well as mood) will get a stop button. It will make it clear if you can click multiple of an effect or not.

You can still specify "element" - for backwards compatibility - but element will be interpreted as synonymous to oneshot. And won't get a stop button.

Please try it out and let me know your thoughts.

**Comment by scooper4711** [comment] 2024-07-05 21:38
resolved with version 1.4.0. The plugin now includes an embedded player

**Closed as completed by scooper4711** 2024-07-05 21:38 UTC
